/*! 

\mainpage Source code to xmov and a few other documents

\section intro Introduction

The code xmov performs molecular dynamics simulation

\section install Installation

Once you have the source files the standard

./configure

make

should generate an executable mdmol in the top level 
directory.  If not let me know

\section help

<a href="xmovhelp.html"> xmov help file </a>

\subsection examples

There are several examples in the examples directory.

*/
